@startuml

title __DTO's Class Diagram__\n

  namespace  {
    namespace k.posam.blog {
      namespace dto {
        class sk.posam.blog.dto.CommentDto {
            - body : String
            - createdAt : Instant
            - id : Long
            - post : String
            - user : String
            + getBody()
            + getCreatedAt()
            + getId()
            + getPost()
            + getUser()
            + setBody()
            + setCreatedAt()
            + setId()
            + setPost()
            + setUser()
        }
      }
    }
  }
  

  namespace  {
    namespace k.posam.blog {
      namespace dto {
        class sk.posam.blog.dto.ImageDto {
            - id : Long
            - name : String
            - picByte : byte[]
            - type : String
            + getId()
            + getName()
            + getPicByte()
            + getType()
            + setId()
            + setName()
            + setPicByte()
            + setType()
        }
      }
    }
  }
  

  namespace  {
    namespace k.posam.blog {
      namespace dto {
        class sk.posam.blog.dto.LoginRequest {
            - password : String
            - username : String
            + getPassword()
            + getUsername()
            + setPassword()
            + setUsername()
        }
      }
    }
  }
  

  namespace  {
    namespace k.posam.blog {
      namespace dto {
        class sk.posam.blog.dto.PostDto {
            - content : String
            - createdAt : Instant
            - id : Long
            - title : String
            - titleImg : String
            - username : String
            + getContent()
            + getCreatedAt()
            + getId()
            + getTitle()
            + getTitleImg()
            + getUsername()
            + setContent()
            + setCreatedAt()
            + setId()
            + setTitle()
            + setTitleImg()
            + setUsername()
        }
      }
    }
  }
  

  namespace  {
    namespace k.posam.blog {
      namespace dto {
        class sk.posam.blog.dto.RegisterRequest {
            - confirmPassword : String
            - email : String
            - name : String
            - password : String
            - registerDate : Instant
            - surename : String
            - username : String
            + getConfirmPassword()
            + getEmail()
            + getName()
            + getPassword()
            + getRegisterDate()
            + getSurename()
            + getUsername()
            + setConfirmPassword()
            + setEmail()
            + setName()
            + setPassword()
            + setRegisterDate()
            + setSurename()
            + setUsername()
        }
      }
    }
  }
  

  namespace  {
    namespace k.posam.blog {
      namespace dto {
        class sk.posam.blog.dto.UserDto {
            - email : String
            - id : Long
            - name : String
            - note : String
            - numberOfPosts : int
            - password : String
            - profilePicture : String
            - registerDate : Instant
            - surename : String
            - username : String
            + getEmail()
            + getId()
            + getName()
            + getNote()
            + getNumberOfPosts()
            + getPassword()
            + getProfilePicture()
            + getRegisterDate()
            + getSurename()
            + getUsername()
            + setEmail()
            + setId()
            + setName()
            + setNote()
            + setNumberOfPosts()
            + setPassword()
            + setProfilePicture()
            + setRegisterDate()
            + setSurename()
            + setUsername()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
